### PR TITLE
Solihull_Assignment

### PR DESCRIPTION
**Pull request by KaranNegi0405**
Solihull_Assignment

### CODE REVIEW

**Review by mssquaretech — CHANGES_REQUESTED** [review]
Please remove .idea folder, log.html, screenshots, output.xml, report.html files

**Review by mssquaretech — COMMENTED** [review]
Can we have variable xpath in keyword - **Select language list** Also better if we replace value in xpaths using replace string keyword of String Library

Rest looks fine.

**Comment by mssquaretech** [comment]
> Can we have variable xpath in keyword - **Select language list** Also better if we replace value in xpaths using replace string keyword of String Library
> 
> Rest looks fine.

The changes are pending... Please make requested changes for review and approval.
Thanks @KaranNegi0405

**Review by KaranNegi0405 — COMMENTED** [review]
Mention directory and files are removed now , please check and approve.

**Review by vikramps095 — APPROVED** [review]
It Looks good. Ok from my end

**Review by Garima2412 — COMMENTED** [review]
Badhiya likhe hain , I got to know how to concatenate statement along with variable we are printing

**Comment by vikramps095** [comment]
> It Looks good. Ok from my end

Please Try to change the Name of the Branch as Name_Project

**Review by mssquaretech — APPROVED** [review]

**Pull request merged**
