### PR TITLE
Narendra- SoliHull Assignment

### PR DESCRIPTION
**Pull request by narendrashakya**
Please review my assignment.

### CODE REVIEW

**Review by mssquaretech — CHANGES_REQUESTED** [review]
Please remove .idea folder, log.html, screenshots, output.xml, report.html files

**Comment by narendrashakya** [comment]
Files and folders removed from branch. Please review.

**Review by mssquaretech — APPROVED** [review]

**Comment by mssquaretech** [comment]
Ready to merge. Need one more reviewer to approve and merge this.
Thanks. @Reviewers, Please approve and merge this.

**Review by vikramps095 — APPROVED** [review]
It Looks good

**Pull request merged**
