### PR TITLE
Narendra_Salesforce Assignment

### PR DESCRIPTION
**Pull request by narendrashakya**
Branch is created with Saleforce assignment.
Please review it.

### CODE REVIEW

**Review by mssquaretech — CHANGES_REQUESTED** [review]
1.  Never commit cred to git. We will pass them from terminal. Pls remove
2. Save button xpath has whitespaces so can we use contains in it.
3. Feature file Given when then statements can have arguments e.g.
When user login with "${user}" and "${password}" 

Rest everything looks perfect. Thanks

**Comment by narendrashakya** [comment]
> 1. Never commit cred to git. We will pass them from terminal. Pls remove
> 2. Save button xpath has whitespaces so can we use contains in it.
> 3. Feature file Given when then statements can have arguments e.g.
>    When user login with "${user}" and "${password}"
> 
> Rest everything looks perfect. Thanks

Below required changes are done. Could you please review and share if any changes required.
1. **[NS: Done]**Never commit cred to git. We will pass them from terminal. Pls remove.
2. **[NS: Done]**Save button xpath has whitespaces so can we use contains in it.
3. **[NS: Done]**Feature file Given when then statements can have arguments.

**Review by mssquaretech — COMMENTED** [review]
Perfect.
Just a small change at line no 22
Provide ${Username} and ${Password}
--> The variable argument should be in quotes
Similarly on User page line no 13. Thanks

**Comment by narendrashakya** [comment]
> Perfect.
> Just a small change at line no 22
> Provide ${Username} and ${Password}
> --> The variable argument should be in quotes
> Similarly on User page line no 13. Thanks

Thanks, Line 22 updated.
Note: I tried with both scenario where variable in quote and not in quote. In both cases it passing the variable.

**Review by mssquaretech — APPROVED** [review]
Approved

**Review by vikramps095 — APPROVED** [review]
It Looks good. Approved.
Thank you

**Pull request merged**
